export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

// Promise
export const REQUEST_ROBOTS_PENDING = 'REQUEST_ROBOTS_PENDING';

// Two states after pending returns
export const REQUEST_ROBOTS_SUCCESS = 'REQUEST_ROBOTS_SUCCESS';
export const REQUEST_ROBOTS_FAILED = 'REQUEST_ROBOTS_FAILED';